### GET ALl Product
GET http://localhost:3000/api/v2/products


### GET only Product
GET http://localhost:3000/api/v2/product


### Create product in database
POST http://localhost:3000/api/v2/products


### Delete product in database
DELETE http://localhost:3000/api/v2/products